package com.integration.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2019-01-03T15:34:03.278+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "RecordInterfaceService", 
                  wsdlLocation = "http://127.0.0.1:8080/VideoLive/ws/record?wsdl",
                  targetNamespace = "http://server.integration.com/") 
public class RecordInterfaceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.integration.com/", "RecordInterfaceService");
    public final static QName RecordInterfacePort = new QName("http://server.integration.com/", "RecordInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/VideoLive/ws/record?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RecordInterfaceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/VideoLive/ws/record?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RecordInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecordInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecordInterfaceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecordInterfaceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecordInterfaceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecordInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RecordInterface
     */
    @WebEndpoint(name = "RecordInterfacePort")
    public RecordInterface getRecordInterfacePort() {
        return super.getPort(RecordInterfacePort, RecordInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecordInterface
     */
    @WebEndpoint(name = "RecordInterfacePort")
    public RecordInterface getRecordInterfacePort(WebServiceFeature... features) {
        return super.getPort(RecordInterfacePort, RecordInterface.class, features);
    }

}
